#include "paraget.h"

ParaGet::ParaGet(string pipesize)
{
    map<string,int> pipesizeControl = {
        {"40inch",1},
        {"32inch",2},
        {"28inch",3},
        {"24inch",4},
        {"16inch",5},
        {"14inch",6},
        {"12inchA",7},
        {"12inchB",7},
        {"12inch",7},
        {"10inchA",8},
        {"10inchB",8},
        {"10inch",8},
        {"08inch",9},
        {"8inch",9},
        {"06inch",10},
        {"6inch",10},
    };
    int caseValue = pipesizeControl[pipesize];
    switch (caseValue) {
    case 1:
        cout<<"ParaGet pipesize: 40inch..."<<endl;

        // initiate this->datpara
        this->datpara.line_num=160;
        this->datpara.bx_end=144+3;
        this->datpara.bx_start=4;
        this->datpara.mile1_cha=157;
        this->datpara.mile2_cha=158;
        this->datpara.mile3_cha=159;
        this->datpara.timechal=2;
        this->datpara.vtime=100*2;
        this->datpara.zxchal=151;
        this->datpara.qjchal=152;
        this->datpara.hxchal=153;
        this->datpara.volchal=3;
        this->datpara.temp1chal=148;
        this->datpara.temp2chal=149;
        this->datpara.temp3chal=150;
        this->datpara.delt_mile=0.002;

        //initiate this->propara
        this->propara.move_length=200;
        this->propara.bx_flag=1;
        this->propara.bx_circle=2;
        this->propara.chanum=144;
        this->propara.volbase=2.9245;
        this->propara.a=214;
        this->propara.r=326+20;
        this->propara.d2=630;
        this->propara.zxflag=1;
        this->propara.qjflag=1;
        this->propara.hxflag=2;
        this->propara.center_0=1;
        this->propara.one_angle=360/this->propara.chanum;
        this->propara.OD=1016;

        // initiate this->prepara
        this->prepara.bianxing_thresh=0.03;
        this->prepara.vstep=250;

        // initiate this->valpara
        this->valpara.lobo_vol=27.2;
        this->valpara.upbo_vol=31.2;
        this->valpara.upbo_zhouxiang=360;
        this->valpara.lobo_zhouxiang=0;
        this->valpara.upbo_qingjiao=90;
        this->valpara.lobo_qingjiao=-90;
        this->valpara.upbo_hangxiang=180;
        this->valpara.lobo_hangxiang=-180;
        this->valpara.upbo_temp=85;
        this->valpara.lobo_temp=20;
        this->valpara.upbo_BX=4.5;
        this->valpara.lobo_BX=0.5;
        this->valpara.window_BX=20;
        this->valpara.thresh_BX=0.0005;
        this->valpara.loss_sensor_BX=ceil(25/(this->propara.OD*M_PI/this->propara.chanum));

        // initiate this->detpara
        this->detpara.blend.thresh1=10;
        this->detpara.blend.thresh2=0.4;
        this->detpara.blend.thresh3=400;
        this->detpara.blend.dis=this->propara.d2;
        this->detpara.weld.threshdiff=0.5;
        this->detpara.weld.vardata=3;
        this->detpara.weld.varstep=10;
        this->detpara.weld.dis=30;
        this->detpara.weld.step=10;
        this->detpara.weld.threshstep=500;
        this->detpara.weld.varseparate=100;
        this->detpara.weld.widthresh=100;
        this->detpara.Con=3;
        this->detpara.detect_thresh=2;
        this->detpara.tee.long_min=100;
        this->detpara.tee.long_max=323.8/2;
        this->detpara.tee.wide_min=40/20;
        this->detpara.tee.wide_max=40/2;
        this->detpara.tee.TH_STD=3;
        this->detpara.tee.area=0;
        this->detpara.tap.long_min=3;
        this->detpara.tap.long_max=50;
        this->detpara.tap.wide_min=0;
        this->detpara.tap.wide_max=4;
        this->detpara.tap.TH_STD=2.85;
        this->detpara.tap.area=0;
        this->detpara.flaw.con=3;
        this->detpara.flaw.area=0;
        this->detpara.flaw.TH_STD=0.35;
        this->detpara.flaw.TH_DET=2;
        this->detpara.oval.smooth_window=2000;
        this->detpara.oval.thresh=1;
        break;
    case 2:
        cout<<"ParaGet pipesize: 32inch..."<<endl;

        this->datpara.line_num=104;
        this->datpara.bx_end=88+3;
        this->datpara.bx_start=4;
        this->datpara.mile1_cha=101;
        this->datpara.mile2_cha=102;
        this->datpara.mile3_cha=103;
        this->datpara.timechal=2;
        this->datpara.vtime=100*2;
        this->datpara.zxchal=95;
        this->datpara.qjchal=96;
        this->datpara.hxchal=97;
        this->datpara.volchal=3;
        this->datpara.temp1chal=92;
        this->datpara.temp2chal=93;
        this->datpara.temp3chal=94;
        this->datpara.delt_mile=0.002;
        this->propara.move_length=round(280.5/2);
        this->propara.bx_flag=1;
        this->propara.bx_circle=2;
        this->propara.chanum=88;
        this->propara.volbase=2.9245;
        this->propara.a =174;
        this->propara.r = 240+20;
        this->propara.d2 = 527.2;
        this->propara.zxflag=2;
        this->propara.qjflag=2;
        this->propara.hxflag=1;
        this->propara.center_0=1;
        this->propara.one_angle=360/this->propara.chanum;
        this->propara.OD=813;
        this->prepara.bianxing_thresh=0.03;
        this->prepara.vstep= 250;
        this->valpara.lobo_vol=27.2;
        this->valpara.upbo_vol=31.2;
        this->valpara.upbo_zhouxiang=360;
        this->valpara.lobo_zhouxiang=0;
        this->valpara.upbo_qingjiao=90;
        this->valpara.lobo_qingjiao=-90;
        this->valpara.upbo_hangxiang=180;
        this->valpara.lobo_hangxiang=-180;
        this->valpara.upbo_temp=85;
        this->valpara.lobo_temp=-20;
        this->valpara.upbo_BX=4.5;
        this->valpara.lobo_BX=0.5;
        this->valpara.window_BX=20;
        this->valpara.thresh_BX=0.0005;
        this->valpara.loss_sensor_BX=ceil(25/(this->propara.OD*M_PI/this->propara.chanum));
        this->detpara.blend.thresh1 = 10;
        this->detpara.blend.thresh2 = 0.4;
        this->detpara.blend.thresh3 = 400;
        this->detpara.blend.dis=this->propara.d2;
        this->detpara.weld.threshdiff = 0.5;
        this->detpara.weld.vardata = 3;
        this->detpara.weld.varstep = 10;
        this->detpara.weld.dis = 30;
        this->detpara.weld.step = 10;
        this->detpara.weld.threshstep = 500;
        this->detpara.weld.varseparate = 100;
        this->detpara.weld.widthresh = 100;
        this->detpara.Con = 3;
        this->detpara.detect_thresh = 2;
        this->detpara.tee.long_min = 100;
        this->detpara.tee.long_max = 323.8/2;
        this->detpara.tee.wide_min = 40/20;
        this->detpara.tee.wide_max = 40/2;
        this->detpara.tee.TH_STD = 3;
        this->detpara.tee.area = 0;
        this->detpara.tap.long_min = 3;
        this->detpara.tap.long_max = 50;
        this->detpara.tap.wide_min = 0;
        this->detpara.tap.wide_max = 4;
        this->detpara.tap.TH_STD = 2.85;
        this->detpara.tap.area = 0;
        this->detpara.flaw.con = 3;
        this->detpara.flaw.area = 0;
        this->detpara.flaw.TH_STD = 0.35;
        this->detpara.flaw.TH_DET = 2;
        this->detpara.oval.smooth_window = 2000;
        this->detpara.oval.thresh = 1;
        break;
    case 3:
        cout<<"ParaGet pipesize: 28inch..."<<endl;
            this->datpara.line_num=88;
            this->datpara.bx_end=75;
            this->datpara.bx_start=4;
            this->datpara.mile1_cha=85;
            this->datpara.mile2_cha=86;
            this->datpara.mile3_cha=87;
            this->datpara.timechal=2;
            this->datpara.vtime=100*2;
            this->datpara.zxchal=79;
            this->datpara.qjchal=80;
            this->datpara.hxchal=81;
            this->datpara.volchal=3;
            this->datpara.temp1chal=76;
            this->datpara.temp2chal=77;
            this->datpara.temp3chal=78;
            this->datpara.delt_mile=0.002;
            this->propara.move_length=round(294.5/2);
            this->propara.bx_flag=1;
            this->propara.bx_circle=2;
            this->propara.chanum=72;
            this->propara.volbase=2.9245;
            this->propara.a =174;
            this->propara.r = 215+20;
            this->propara.d2 = 375.6;
            this->propara.zxflag=2;
            this->propara.qjflag=2;
            this->propara.hxflag=1;
            this->propara.center_0=1;
            this->propara.one_angle=360/this->propara.chanum;
            this->propara.OD=711;
            this->prepara.bianxing_thresh=0.03;
            this->prepara.vstep= 250;
            this->valpara.lobo_vol=27.2;
            this->valpara.upbo_vol=31.2;
            this->valpara.upbo_zhouxiang=360;
            this->valpara.lobo_zhouxiang=0;
            this->valpara.upbo_qingjiao=90;
            this->valpara.lobo_qingjiao=-90;
            this->valpara.upbo_hangxiang=180;
            this->valpara.lobo_hangxiang=-180;
            this->valpara.upbo_temp=85;
            this->valpara.lobo_temp=-20;
            this->valpara.upbo_BX=4.5;
            this->valpara.lobo_BX=0.5;
            this->valpara.window_BX=20;
            this->valpara.thresh_BX=0.0005;
            this->valpara.loss_sensor_BX=ceil(25/(this->propara.OD*M_PI/this->propara.chanum));
            this->detpara.blend.thresh1 = 10;
            this->detpara.blend.thresh2 = 0.4;
            this->detpara.blend.thresh3 = 400;
            this->detpara.blend.dis=this->propara.d2;
            this->detpara.weld.threshdiff = 0.5;
            this->detpara.weld.vardata = 3;
            this->detpara.weld.varstep = 10;
            this->detpara.weld.dis = 30;
            this->detpara.weld.step = 10;
            this->detpara.weld.threshstep = 500;
            this->detpara.weld.varseparate = 100;
            this->detpara.weld.widthresh = 100;
            this->detpara.Con = 3;
            this->detpara.detect_thresh = 2;
            this->detpara.tee.long_min = 100;
            this->detpara.tee.long_max = 323.8/2;
            this->detpara.tee.wide_min = 40/20;
            this->detpara.tee.wide_max = 40/2;
            this->detpara.tee.TH_STD = 3;
            this->detpara.tee.area = 0;
            this->detpara.tap.long_min = 3;
            this->detpara.tap.long_max = 50;
            this->detpara.tap.wide_min = 0;
            this->detpara.tap.wide_max = 4;
            this->detpara.tap.TH_STD = 2.85;
            this->detpara.tap.area = 0;
            this->detpara.flaw.con = 3;
            this->detpara.flaw.area = 0;
            this->detpara.flaw.TH_STD = 0.35;
            this->detpara.flaw.TH_DET = 2;
            this->detpara.oval.smooth_window = 2000;
            this->detpara.oval.thresh = 1;

        break;
    case 4:
        cout<<"ParaGet pipesize: 24inch..."<<endl;
        datpara.line_num=80;
            datpara.bx_end=67;
            datpara.bx_start=4;
            datpara.mile1_cha=77;
            datpara.mile2_cha=78;
            datpara.mile3_cha=79;
            datpara.timechal=2;
            datpara.vtime=100*2;
            datpara.zxchal=71;
            datpara.qjchal=72;
            datpara.hxchal=73;
            datpara.volchal=3;
            datpara.temp1chal=68;
            datpara.temp2chal=69;
            datpara.temp3chal=70;
            datpara.delt_mile=0.002;
            propara.move_length=round(467/2);
            propara.bx_flag=1;
            propara.bx_circle=2;
            propara.chanum=64;
            propara.volbase=2.9502;
            propara.a =129;
            propara.r = 165+20;
            propara.d2 = NULL;
            propara.zxflag=NULL;
            propara.qjflag=NULL;
            propara.hxflag=NULL;
            propara.center_0=1;
            propara.one_angle=360/64;
            propara.OD=610;
            prepara.bianxing_thresh=0.03;
            prepara.vstep= 250;
            valpara.lobo_vol=27.2;
            valpara.upbo_vol=31.2;
            valpara.upbo_zhouxiang=360;
            valpara.lobo_zhouxiang=0;
            valpara.upbo_qingjiao=90;
            valpara.lobo_qingjiao=-90;
            valpara.upbo_hangxiang=180;
            valpara.lobo_hangxiang=-180;
            valpara.upbo_temp=85;
            valpara.lobo_temp=-20;
            valpara.upbo_BX=4.5;
            valpara.lobo_BX=0.5;
            valpara.window_BX=20;
            valpara.thresh_BX=0.0005;
            valpara.loss_sensor_BX=1;

            detpara.blend.thresh1 = 10;
            detpara.blend.thresh2 = 0.4;
            detpara.blend.thresh3 = 400;
            detpara.blend.od = propara.OD;
            detpara.blend.dis=this->propara.d2;

            detpara.weld.threshdiff = 0.5;
            detpara.weld.vardata = 3;
            detpara.weld.varstep = 10;
            detpara.weld.dis = 30;
            detpara.weld.step = 10;
            detpara.weld.threshstep = 500;
            detpara.weld.varseparate = 100;
            detpara.weld.widthresh = 100;
            detpara.Con = 3;
            detpara.detect_thresh = 2;
            detpara.tee.long_min = 100;
            detpara.tee.long_max = 323.8/2;
            detpara.tee.wide_min = 40/20;
            detpara.tee.wide_max = 40/2;
            detpara.tee.TH_STD = 3;
            detpara.tee.area = 0;
            detpara.tap.long_min = 3;
            detpara.tap.long_max = 50;
            detpara.tap.wide_min = 0;
            detpara.tap.wide_max = 4;
            detpara.tap.TH_STD = 2.85;
            detpara.tap.area = 0;
            detpara.flaw.con = 3;
            detpara.flaw.area = 0;
            detpara.flaw.TH_STD = 0.35;
            detpara.flaw.TH_DET = 2;
            detpara.oval.smooth_window = 2000;
            detpara.oval.thresh = 1;
        break;
    case 5:
        cout<<"ParaGet pipesize: 16inch..."<<endl;

        datpara.line_num=51;
        datpara.bx_end=39;
        datpara.bx_start=4;
        datpara.mile1_cha=49;
        datpara.mile2_cha=50;
        datpara.mile3_cha=51;
        datpara.timechal=2;
        datpara.vtime=100*2;
        datpara.zxchal=43;
        datpara.qjchal=44;
        datpara.hxchal=45;
        datpara.volchal=3;
        datpara.temp1chal=40;
        datpara.temp2chal=41;
        datpara.temp3chal=42;
        datpara.delt_mile=0.002;
        propara.move_length=0;
        propara.bx_flag=1;
        propara.bx_circle=1;
        propara.chanum=36;
        propara.volbase=NULL;
        propara.a =100;
        propara.r = 127.7+5;
        propara.d2 = 43;
        propara.zxflag=2;
        propara.qjflag=2;
        propara.hxflag=1;
        propara.center_0=1;
        propara.one_angle=360/36;
        propara.OD=406;
        prepara.bianxing_thresh=0.03;
        prepara.vstep= 250;
        valpara.lobo_vol=27.2;
        valpara.upbo_vol=31.2;
        valpara.upbo_zhouxiang=360;
        valpara.lobo_zhouxiang=0;
        valpara.upbo_qingjiao=90;
        valpara.lobo_qingjiao=-90;
        valpara.upbo_hangxiang=180;
        valpara.lobo_hangxiang=-180;
        valpara.upbo_temp=85;
        valpara.lobo_temp=-20;
        valpara.upbo_BX=4.5;
        valpara.lobo_BX=0.5;
        valpara.window_BX=20;
        valpara.thresh_BX=0.0005;
        valpara.loss_sensor_BX=1;

        detpara.blend.thresh1 = 10;
        detpara.blend.thresh2 = 0.4;
        detpara.blend.thresh3 = 400;
        detpara.blend.od = propara.OD;
        detpara.blend.dis=this->propara.d2;
        detpara.weld.threshdiff = 0.5;
        detpara.weld.vardata = 3;
        detpara.weld.varstep = 10;
        detpara.weld.dis = 30;
        detpara.weld.step = 10;
        detpara.weld.threshstep = 500;
        detpara.weld.varseparate = 100;
        detpara.weld.widthresh = 100;
        detpara.Con = 3;
        detpara.detect_thresh = 2;
        detpara.tee.long_min = 100;
        detpara.tee.long_max = 323.8/2;
        detpara.tee.wide_min = 40/20;
        detpara.tee.wide_max = 40/2;
        detpara.tee.TH_STD = 3;
        detpara.tee.area = 0;
        detpara.tap.long_min = 3;
        detpara.tap.long_max = 50;
        detpara.tap.wide_min = 0;
        detpara.tap.wide_max = 4;
        detpara.tap.TH_STD = 2.85;
        detpara.tap.area = 0;
        detpara.flaw.con = 3;
        detpara.flaw.area = 0;
        detpara.flaw.TH_STD = 0.35;
        detpara.flaw.TH_DET = 2;
        detpara.oval.smooth_window = 2000;
        detpara.oval.thresh = 1;
        break;
    case 6:
        cout<<"ParaGet pipesize: 14inch..."<<endl;

        datpara.line_num=56;
        datpara.bx_end=43;
        datpara.bx_start=4;
        datpara.mile1_cha=53;
        datpara.mile2_cha=54;
        datpara.mile3_cha=55;
        datpara.timechal=2;
        datpara.vtime=100*2;
        datpara.zxchal=47;
        datpara.qjchal=48;
        datpara.hxchal=49;
        datpara.volchal=3;
        datpara.temp1chal=44;
        datpara.temp2chal=45;
        datpara.temp3chal=46;
        datpara.delt_mile=0.002;
        propara.move_length=round(148/2);
        propara.bx_flag=1;
        propara.bx_circle=2;
        propara.chanum=40;
        propara.volbase=2.9502;
        propara.a =108;
        propara.r = 104+8.5;
        propara.d2 = 172;
        propara.zxflag=2;
        propara.qjflag=2;
        propara.hxflag=1;
        propara.center_0=1;
        propara.one_angle=360/40;
        propara.OD=355.09;
        prepara.bianxing_thresh=0.03;
        prepara.vstep= 250;
        valpara.lobo_vol=20.4;
        valpara.upbo_vol=23.4;
        valpara.upbo_zhouxiang=360;
        valpara.lobo_zhouxiang=0;
        valpara.upbo_qingjiao=90;
        valpara.lobo_qingjiao=-90;
        valpara.upbo_hangxiang=180;
        valpara.lobo_hangxiang=-180;
        valpara.upbo_temp=85;
        valpara.lobo_temp=-20;
        valpara.upbo_BX=4.5;
        valpara.lobo_BX=1.3;
        valpara.window_BX=20;
        valpara.thresh_BX=0.0005;
        valpara.loss_sensor_BX=1;

        detpara.blend.thresh1 = 10;
        detpara.blend.thresh2 = 0.4;
        detpara.blend.thresh3 = 400;
        detpara.blend.od = propara.OD;
        detpara.blend.dis=this->propara.d2;
        detpara.weld.threshdiff = 0.5;
        detpara.weld.vardata = 3;
        detpara.weld.varstep = 10;
        detpara.weld.dis = 30;
        detpara.weld.step = 10;
        detpara.weld.threshstep = 500;
        detpara.weld.varseparate = 100;
        detpara.weld.widthresh = 100;
        detpara.Con = 3;
        detpara.detect_thresh = 2;
        detpara.tee.long_min = 100;
        detpara.tee.long_max = 323.8/2;
        detpara.tee.wide_min = 40/20;
        detpara.tee.wide_max = 40/2;
        detpara.tee.TH_STD = 3;
        detpara.tee.area = 0;
        detpara.tap.long_min = 3;
        detpara.tap.long_max = 50;
        detpara.tap.wide_min = 0;
        detpara.tap.wide_max = 4;
        detpara.tap.TH_STD = 2.85;
        detpara.tap.area = 0;
        detpara.flaw.con = 3;
        detpara.flaw.area = 0;
        detpara.flaw.TH_STD = 0.35;
        detpara.flaw.TH_DET = 2;
        detpara.oval.smooth_window = 2000;
        detpara.oval.thresh = 1;
        break;
    case 7:
        cout<<"ParaGet pipesize: 12inch..."<<endl;
            datpara.line_num=56;
            datpara.bx_end=43;
            datpara.bx_start=4;
            datpara.mile1_cha=53;
            datpara.mile2_cha=54;
            datpara.mile3_cha=55;
            datpara.timechal=2;
            datpara.zxchal=47;
            datpara.qjchal=48;
            datpara.hxchal=49;
            datpara.volchal=3;
            datpara.temp1chal=44;
            datpara.temp2chal=45;
            datpara.temp3chal=46;
            datpara.delt_mile=0.002;
            propara.move_length=round(141/2);
            propara.bx_flag=1;
            propara.bx_circle=2;
            propara.chanum=40;
            if(pipesize=="12inchA"){
                datpara.vtime=10*2;
                propara.volbase=2.9247;
                propara.a =121;
            }

            else{
                datpara.vtime=100*2;
                propara.volbase=2.5502;
                propara.a =100;
            }
            propara.r = 87+5;
            propara.d2 = 574;
            propara.zxflag=2;
            propara.qjflag=2;
            propara.hxflag=1;
            propara.center_0=1;
            propara.one_angle=360/40;
            propara.OD=323.8;
            prepara.bianxing_thresh=0.03;
            prepara.vstep= 250;
            valpara.lobo_vol=23.8;
            valpara.upbo_vol=27.3;
            valpara.upbo_zhouxiang=360;
            valpara.lobo_zhouxiang=0;
            valpara.upbo_qingjiao=90;
            valpara.lobo_qingjiao=-90;
            valpara.upbo_hangxiang=180;
            valpara.lobo_hangxiang=-180;
            valpara.upbo_temp=85;
            valpara.lobo_temp=-20;
            valpara.upbo_BX=4.5;
            valpara.lobo_BX=0.1;
            valpara.window_BX=20;
            valpara.thresh_BX=0.0005;
            valpara.loss_sensor_BX=1;

            detpara.blend.thresh1 = 10;
            detpara.blend.thresh2 = 0.4;
            detpara.blend.thresh3 = 400;
            detpara.blend.od = propara.OD;
            detpara.blend.dis=this->propara.d2;
            detpara.weld.threshdiff = 0.5;
            detpara.weld.vardata = 3;
            detpara.weld.varstep = 10;
            detpara.weld.dis = 30;
            detpara.weld.step = 10;
            detpara.weld.threshstep = 500;
            detpara.weld.varseparate = 100;
            detpara.weld.widthresh = 100;
            detpara.Con = 3;
            detpara.detect_thresh = 2;
            detpara.tee.long_min = 100;
            detpara.tee.long_max = 323.8/2;
            detpara.tee.wide_min = 40/20;
            detpara.tee.wide_max = 40/2;
            detpara.tee.TH_STD = 3;
            detpara.tee.area = 0;
            detpara.tap.long_min = 3;
            detpara.tap.long_max = 50;
            detpara.tap.wide_min = 0;
            detpara.tap.wide_max = 4;
            detpara.tap.TH_STD = 2.85;
            detpara.tap.area = 0;
            detpara.flaw.con = 3;
            detpara.flaw.area = 0;
            detpara.flaw.TH_STD = 0.35;
            detpara.flaw.TH_DET = 2;
            detpara.oval.smooth_window = 2000;
            detpara.oval.thresh = 1;
        break;
    case 8:
        cout<<"ParaGet pipesize: 10inch..."<<endl;

        datpara.line_num=52;
            datpara.bx_end=39;
            datpara.bx_start=4;
            datpara.mile1_cha=49;
            datpara.mile2_cha=50;
            datpara.mile3_cha=51;
            datpara.timechal=2;
            datpara.vtime=100*2;
            datpara.zxchal=43;
            datpara.qjchal=44;
            datpara.hxchal=45;
            datpara.volchal=3;
            datpara.temp1chal=40;
            datpara.temp2chal=41;
            datpara.temp3chal=42;
            datpara.delt_mile=0.002;
            propara.move_length=round(112/2);
            if(pipesize=="10inchA"){
                propara.bx_flag=1;
            }

            else{
                propara.bx_flag=2;
            }

            propara.bx_circle=2;
            propara.chanum=36;
            propara.volbase=3.1841;
            propara.a =90;
            propara.r = 79+8.5;
            propara.d2 = 85;
            propara.zxflag=2;
            propara.qjflag=2;
            propara.hxflag=1;
            propara.center_0=18;
            propara.one_angle=360/36;
            propara.OD=273;
            prepara.vstep= 250;
            prepara.bianxing_thresh=0.03;
            valpara.lobo_vol=9;
            valpara.upbo_vol=36;
            valpara.upbo_zhouxiang=360;
            valpara.lobo_zhouxiang=0;
            valpara.upbo_qingjiao=90;
            valpara.lobo_qingjiao=-90;
            valpara.upbo_hangxiang=180;
            valpara.lobo_hangxiang=-180;
            valpara.upbo_temp=80;
            valpara.lobo_temp=INT_MIN;
            valpara.upbo_BX=INT_MAX;
            valpara.lobo_BX=0.3;
            valpara.window_BX=20;
            valpara.thresh_BX=0.0005;
            valpara.loss_sensor_BX=1;

            detpara.blend.thresh1 = 10;
            detpara.blend.thresh2 = 0.4;
            detpara.blend.thresh3 = 400;
            detpara.blend.od = propara.OD;
            detpara.blend.dis=this->propara.d2;
            detpara.weld.threshdiff = 0.5;
            detpara.weld.vardata = 3;
            detpara.weld.varstep = 10;
            detpara.weld.dis = 30;
            detpara.weld.step = 10;
            detpara.weld.threshstep = 500;
            detpara.weld.varseparate = 100;
            detpara.weld.widthresh = 100;
            detpara.Con = 3;
            detpara.detect_thresh = 2;
            detpara.tee.long_min = 100;
            detpara.tee.long_max = 323.8/2;
            detpara.tee.wide_min = 40/20;
            detpara.tee.wide_max = 40/2;
            detpara.tee.TH_STD = 3;
            detpara.tee.area = 0;
            detpara.tap.long_min = 3;
            detpara.tap.long_max = 50;
            detpara.tap.wide_min = 0;
            detpara.tap.wide_max = 4;
            detpara.tap.TH_STD = 2.85;
            detpara.tap.area = 0;
            detpara.flaw.con = 3;
            detpara.flaw.area = 0;
            detpara.flaw.TH_STD = 0.35;
            detpara.flaw.TH_DET = 2;
            detpara.oval.smooth_window = 2000;
            detpara.oval.thresh = 1;
        break;
    case 9:
        cout<<"ParaGet pipesize: 08inch..."<<endl;

        datpara.line_num=46;
        datpara.bx_end=33;
        datpara.bx_start=4;
        datpara.mile1_cha=43;
        datpara.mile2_cha=44;
        datpara.mile3_cha=45;
        datpara.timechal=2;
        datpara.vtime=100*2;
        datpara.zxchal=37;
        datpara.qjchal=38;
        datpara.hxchal=39;
        datpara.volchal=3;
        datpara.temp1chal=34;
        datpara.temp2chal=35;
        datpara.temp3chal=36;
        datpara.delt_mile=0.002;
        propara.move_length=round(87/2);
        propara.bx_flag=1;
        propara.bx_circle=2;
        propara.chanum=30;
        propara.volbase=3.221;
        propara.a =56;
        propara.r = 66+7.5;
        propara.d2 = 77.25;
        propara.zxflag=2;
        propara.qjflag=2;
        propara.hxflag=1;
        propara.center_0=1;
        propara.one_angle=360/30;
        propara.OD=219;
        prepara.bianxing_thresh=0.03;
        prepara.vstep= 250;
        valpara.lobo_vol=18;
        valpara.upbo_vol=30;
        valpara.upbo_zhouxiang=360;
        valpara.lobo_zhouxiang=0;
        valpara.upbo_qingjiao=90;
        valpara.lobo_qingjiao=-90;
        valpara.upbo_hangxiang=180;
        valpara.lobo_hangxiang=-180;
        valpara.upbo_temp=80;
        valpara.lobo_temp=INT_MIN;
        valpara.upbo_BX=INT_MAX;
        valpara.lobo_BX=0.3;
        valpara.window_BX=20;
        valpara.thresh_BX=0.0005;
        valpara.loss_sensor_BX=1;

        detpara.blend.thresh1 = 10;
        detpara.blend.thresh2 = 0.4;
        detpara.blend.thresh3 = 400;
        detpara.blend.od = 323.8;
        detpara.blend.dis = 574;
        detpara.weld.threshdiff = 0.5;
        detpara.weld.vardata = 3;
        detpara.weld.varstep = 10;
        detpara.weld.dis = 30;
        detpara.weld.step = 10;
        detpara.weld.threshstep = 500;
        detpara.weld.varseparate = 100;
        detpara.weld.widthresh = 100;
        detpara.Con = 3;
        detpara.detect_thresh = 2;
        detpara.tee.long_min = 100;
        detpara.tee.long_max = 323.8/2;
        detpara.tee.wide_min = 40/20;
        detpara.tee.wide_max = 40/2;
        detpara.tee.TH_STD = 3;
        detpara.tee.area = 0;
        detpara.tap.long_min = 3;
        detpara.tap.long_max = 50;
        detpara.tap.wide_min = 0;
        detpara.tap.wide_max = 4;
        detpara.tap.TH_STD = 2.85;
        detpara.tap.area = 0;
        detpara.flaw.con = 3;
        detpara.flaw.area = 0;
        detpara.flaw.TH_STD = 0.35;
        detpara.flaw.TH_DET = 2;
        detpara.oval.smooth_window = 2000;
        detpara.oval.thresh = 1;
        break;
    case 10:
        cout<<"ParaGet pipesize: 06inch..."<<endl;
        datpara.line_num=40;
        datpara.bx_end=27;
        datpara.bx_start=4;
        datpara.mile1_cha=37;
        datpara.mile2_cha=38;
        datpara.mile3_cha=39;
        datpara.timechal=2;
        datpara.vtime=100*2;
        datpara.zxchal=31;
        datpara.qjchal=32;
        datpara.hxchal=33;
        datpara.volchal=3;
        datpara.temp1chal=28;
        datpara.temp2chal=29;
        datpara.temp3chal=30;
        datpara.delt_mile=0.002;
        propara.move_length=round(87/2);
        propara.bx_flag=1;
        propara.bx_circle=2;
        propara.chanum=24;
        propara.volbase=3.6507;
        propara.a =56;
        propara.r = 44.5+7.5;
        propara.d2 = 518;
        propara.zxflag=2;
        propara.qjflag=2;
        propara.hxflag=1;
        propara.center_0=1;
        propara.one_angle=360/24;
        propara.OD=168;
        prepara.bianxing_thresh=0.03;
        prepara.vstep= 250;
        valpara.lobo_vol=18;
        valpara.upbo_vol=30;
        valpara.upbo_zhouxiang=360;
        valpara.lobo_zhouxiang=0;
        valpara.upbo_qingjiao=90;
        valpara.lobo_qingjiao=-90;
        valpara.upbo_hangxiang=180;
        valpara.lobo_hangxiang=-180;
        valpara.upbo_temp=80;
        valpara.lobo_temp=INT_MIN;
        valpara.upbo_BX=INT_MAX;
        valpara.lobo_BX=0.3;
        valpara.window_BX=20;
        valpara.thresh_BX=0.0005;
        valpara.loss_sensor_BX=1;

        detpara.blend.thresh1 = 10;
        detpara.blend.thresh2 = 0.4;
        detpara.blend.thresh3 = 400;
        detpara.blend.od = 168;
        detpara.blend.dis = 518;
        detpara.weld.threshdiff = 0.5;
        detpara.weld.vardata = 3;
        detpara.weld.varstep = 10;
        detpara.weld.dis = 30;
        detpara.weld.step = 10;
        detpara.weld.threshstep = 500;
        detpara.weld.varseparate = 100;
        detpara.weld.widthresh = 100;
        detpara.Con = 3;
        detpara.detect_thresh = 2;
        detpara.tee.long_min = 100;
        detpara.tee.long_max = 323.8/2;
        detpara.tee.wide_min = 40/20;
        detpara.tee.wide_max = 40/2;
        detpara.tee.TH_STD = 3;
        detpara.tee.area = 0;
        detpara.tap.long_min = 3;
        detpara.tap.long_max = 50;
        detpara.tap.wide_min = 0;
        detpara.tap.wide_max = 4;
        detpara.tap.TH_STD = 2.85;
        detpara.tap.area = 0;
        detpara.flaw.con = 3;
        detpara.flaw.area = 0;
        detpara.flaw.TH_STD = 0.35;
        detpara.flaw.TH_DET = 2;
        detpara.oval.smooth_window = 2000;
        detpara.oval.thresh = 1;
        break;

    default:
        break;
    }
}
